services:

  mkdocs:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: mkdocs-dev
    container_name: mkdocs-dev
    volumes:
      - ..:/docs
    working_dir: /docs
    tty: true
    command: /bin/bash
    ports:
      - 8080:8080
