FROM python:3.11.1-slim-bullseye

RUN adduser -q --gecos "" --disabled-login mkuser \
    && pip install mkdocs mkdocs-material fontawesome-markdown mdx_unimoji python-markdown-math pymdown-extensions
