version: '3'
services:

  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    image: mkdocs
    container_name: mkdocs
    volumes:
      - ${PWD}:/docs
    working_dir: /docs
    tty: true
    command: /bin/bash
    ports:
      - 8080:8080
